# Generated by Django 6.0.1 on 2026-01-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BASIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basic')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(blank=True)),
                ('abonnement_type', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='FREE', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('customer_type', models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('JOBLESS', 'JOBLESS')], default='JOBLESS', max_length=20)),
            ],
            bases=('api.basic',),
        ),
    ]
